### PR TITLE
Event information returning for listeners

### PR DESCRIPTION
**Pull request by renie**
Event information like number of files already downloaded and total files to download is now being passed to listeners.

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks Renie! Could you maybe add a test to it, please?

**Comment by gr2m** [comment]
And one last thing (don't worry I can take care of this myself). Could you do separate commits for the test and the added feature, like so?

- test: pass applicationCache event to appCache event handlers
- feat: pass applicationCache event to appCache event handlers

The reason is that we use [semantic-release](https://www.npmjs.com/package/semantic-release) for automated releasing :)

**Comment by renie** [comment]
Sure, I'll do this. Thanks!

**Comment by renie** [comment]
Can you check if I did this right? Thanks for helping =D

**Comment by gr2m** [comment]
Thank you for taking the time :) I'll have a look at it today, latest tomorrow

**Comment by gr2m** [comment]
looks like `event.loaded` and `event.total` is not set in Firefox, tested in latest stable version 38. Could you check that please? Works fine in Chrome

**Comment by renie** [comment]
Hey, sorry about this delay,

About this issue I found that ProgressEvent exists on Firefox and it has those attributes [[ref. link]](https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent).

The problem is the event dispatched by progress on applicationCache is just a normal Event, and not a ProgressEvent,

So what do you think: should I change the test or the output of log on html?

**Comment by gr2m** [comment]
Hey @renie just fyi I'm moving to Boston tomorrow and will need a few days to get back to you. Hope you can wait, I definitely should get back to you by the end of the week

**Comment by gr2m** [comment]
the ProgressEvent is not what you get from applicationCache, so we can't use that here, I'm afraid. I fear there is no way to get `loaded` / `total` cross browser.

**Comment by renie** [comment]
Actually [W3C specification](http://www.w3.org/TR/2011/WD-html5-20110525/offline.html#appcacheevents) says, and chrome follows this, that progress event should dispatch a ProgressEvent.

Maybe there is not a way to get [loaded/total](https://xhr.spec.whatwg.org/#interface-progressevent) cross browser, but this feature exists as we can see in those links I listed above.

So, of course this is just an opinion (your code your rules =D ), I think that the decision about which browser will be supported should be a problem for people who are using your library. Your part is just 'teach applicationCache some good manners', and this is being done very well! 

Therefore, if I was you I would let the original events bubble up. What will be done with this is not up to you.

(sorry for insisting on this)

**Comment by gr2m** [comment]
I don’t want to drop support for the browsers that are currently supported. I recommend you make a fork and we can link it in the README, would that work?

**Pull request closed without merging**
